export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const userConstants = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",

  GET_ALL_USERS_REQUEST: " GET_ALL_USERS_REQUEST",
  GET_ALL_USERS_SUCCESS: " GET_ALL_USERS_SUCCESS",
  GET_ALL_USERS_FAILURE: " GET_ALL_USERS_FAILURE",

  GET_USER_DETAIL_BY_ID_REQUEST: " GET_USER_DETAIL_BY_ID_REQUEST",
  GET_USER_DETAIL_BY_ID_SUCCESS: " GET_USER_DETAIL_BY_ID_SUCCESS",
  GET_USER_DETAIL_BY_ID_FAILURE: " GET_USER_DETAIL_BY_ID_FAILURE",
};

export const enterpriseConstants = {
  GET_ALL_ENTERPRISES_REQUEST: " GET_ALL_ENTERPRISES_REQUEST",
  GET_ALL_ENTERPRISES_SUCCESS: " GET_ALL_ENTERPRISES_SUCCESS",
  GET_ALL_ENTERPRISES_FAILURE: " GET_ALL_ENTERPRISES_FAILURE",

  ADD_NEW_ENTERPRISES_REQUEST: "ADD_NEW_ENTERPRISES_REQUEST",
  ADD_NEW_ENTERPRISES_SUCCESS: "ADD_NEW_ENTERPRISES_SUCCESS",
  ADD_NEW_ENTERPRISES_FAILURE: "ADD_NEW_ENTERPRISES_FAILURE",

  EDIT_ENTERPRIESE_REQUEST: "EDIT_ENTERPRIESE_REQUEST",
  EDIT_ENTERPRIESE_SUCCESS: "EDIT_ENTERPRIESE_SUCCESS",
  EDIT_ENTERPRIESE_FAILURE: "EDIT_ENTERPRIESE_FAILURE",

  DELETE_ENTERPRIESE_REQUEST: "DELETE_ENTERPRIESE_REQUEST",
  DELETE_ENTERPRIESE_SUCCESS: "DELETE_ENTERPRIESE_SUCCESS",
  DELETE_ENTERPRIESE_FAILURE: "DELETE_ENTERPRIESE_FAILURE",

  GET_ENTERPRISES_DETAILS_BY_ID_REQUEST:
    "GET_ENTERPRISES_DETAILS_BY_ID_REQUEST",
  GET_ENTERPRISES_DETAILS_BY_ID_SUCCESS:
    "GET_ENTERPRISES_DETAILS_BY_ID_SUCCESS",
  GET_ENTERPRISES_DETAILS_BY_ID_FAILURE:
    "GET_ENTERPRISES_DETAILS_BY_ID_FAILURE",
};

export const routerConstants = {
  GET_ALL_ROUTES_REQUEST: " GET_ALL_ROUTES_REQUEST",
  GET_ALL_ROUTES_SUCCESS: " GET_ALL_ROUTES_SUCCESS",
  GET_ALL_ROUTES_FAILURE: " GET_ALL_ROUTES_FAILURE",

  ADD_NEW_ROUTE_REQUEST: "ADD_NEW_ROUTE_REQUEST",
  ADD_NEW_ROUTE_SUCCESS: "ADD_NEW_ROUTE_SUCCESS",
  ADD_NEW_ROUTE_FAILURE: "ADD_NEW_ROUTE_FAILURE",

  EDIT_ROUTE_REQUEST: "EDIT_ROUTE_REQUEST",
  EDIT_ROUTE_SUCCESS: "EDIT_ROUTE_SUCCESS",
  EDIT_ROUTE_FAILURE: "EDIT_ROUTE_FAILURE",

  DELETE_ROUTE_REQUEST: "DELETE_ROUTE_REQUEST",
  DELETE_ROUTE_SUCCESS: "DELETE_ROUTE_SUCCESS",
  DELETE_ROUTE_FAILURE: "DELETE_ROUTE_FAILURE",

  GET_ROUTES_DETAILS_BY_ID_REQUEST: "GET_ROUTES_DETAILS_BY_ID_REQUEST",
  GET_ROUTES_DETAILS_BY_ID_SUCCESS: "GET_ROUTES_DETAILS_BY_ID_SUCCESS",
  GET_ROUTES_DETAILS_BY_ID_FAILURE: "GET_ROUTES_DETAILS_BY_ID_FAILURE",
};

export const cityConstants = {
  GET_ALL_CITIES_REQUEST: " GET_ALL_CITIES_REQUEST",
  GET_ALL_CITIES_SUCCESS: " GET_ALL_CITIES_SUCCESS",
  GET_ALL_CITIES_FAILURE: " GET_ALL_CITIES_FAILURE",
};

export const vehicleConstants = {
  GET_ALL_VEHICLES_REQUEST: " GET_ALL_VEHICLES_REQUEST",
  GET_ALL_VEHICLES_SUCCESS: " GET_ALL_VEHICLES_SUCCESS",
  GET_ALL_VEHICLES_FAILURE: " GET_ALL_VEHICLES_FAILURE",

  ADD_NEW_VEHICLE_REQUEST: "ADD_NEW_VEHICLE_REQUEST",
  ADD_NEW_VEHICLE_SUCCESS: "ADD_NEW_VEHICLE_SUCCESS",
  ADD_NEW_VEHICLE_FAILURE: "ADD_NEW_VEHICLE_FAILURE",

  EDIT_VEHICLE_REQUEST: "EDIT_VEHICLE_REQUEST",
  EDIT_VEHICLE_SUCCESS: "EDIT_VEHICLE_SUCCESS",
  EDIT_VEHICLE_FAILURE: "EDIT_VEHICLE_FAILURE",

  DELETE_VEHICLE_REQUEST: "DELETE_VEHICLE_REQUEST",
  DELETE_VEHICLE_SUCCESS: "DELETE_VEHICLE_SUCCESS",
  DELETE_VEHICLE_FAILURE: "DELETE_VEHICLE_FAILURE",
};

export const tripConstants = {
  ADD_NEW_TRIP_REQUEST: "ADD_NEW_TRIP_REQUEST",
  ADD_NEW_TRIP_SUCCESS: "ADD_NEW_TRIP_SUCCESS",
  ADD_NEW_TRIP_FAILURE: "ADD_NEW_TRIP_FAILURE",

  GET_TRIP_DETAILS_BY_ID_REQUEST: "GET_TRIP_DETAILS_BY_ID_REQUEST",
  GET_TRIP_DETAILS_BY_ID_SUCCESS: "GET_TRIP_DETAILS_BY_ID_SUCCESS",
  GET_TRIP_DETAILS_BY_ID_FAILURE: "GET_TRIP_DETAILS_BY_ID_FAILURE",
};

export const steersmanConstants = {
  ADD_NEW_STEERSMAN_REQUEST: "ADD_NEW_STEERSMAN_REQUEST",
  ADD_NEW_STEERSMAN_SUCCESS: "ADD_NEW_STEERSMAN_SUCCESS",
  ADD_NEW_STEERSMAN_FAILURE: "ADD_NEW_STEERSMAN_FAILURE",
};
