export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const userConstants = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
};

export const enterpriseConstants = {
  GET_ALL_ENTERPRISES_REQUEST: " GET_ALL_ENTERPRISES_REQUEST",
  GET_ALL_ENTERPRISES_SUCCESS: " GET_ALL_ENTERPRISES_SUCCESS",
  GET_ALL_ENTERPRISES_FAILURE: " GET_ALL_ENTERPRISES_FAILURE",

  ADD_NEW_ENTERPRISES_REQUEST: "ADD_NEW_ENTERPRISES_REQUEST",
  ADD_NEW_ENTERPRISES_SUCCESS: "ADD_NEW_ENTERPRISES_SUCCESS",
  ADD_NEW_ENTERPRISES_FAILURE: "ADD_NEW_ENTERPRISES_FAILURE",

  EDIT_ENTERPRIESE_REQUEST: "EDIT_ENTERPRIESE_REQUEST",
  EDIT_ENTERPRIESE_SUCCESS: "EDIT_ENTERPRIESE_SUCCESS",
  EDIT_ENTERPRIESE_FAILURE: "EDIT_ENTERPRIESE_FAILURE",

  DELETE_ENTERPRIESE_REQUEST: "DELETE_ENTERPRIESE_REQUEST",
  DELETE_ENTERPRIESE_SUCCESS: "DELETE_ENTERPRIESE_SUCCESS",
  DELETE_ENTERPRIESE_FAILURE: "DELETE_ENTERPRIESE_FAILURE",
};
