export const ANALYTICS_REQUEST = "ANALYTICS_REQUEST"
export const ANALYTICS_SUCCESS = "ANALYTICS_SUCCESS"
export const ANALYTICS_FAIL = "ANALYTICS_FAIL"

export const ANALYTICS_CHART_REQUEST = "ANALYTICS_CHART_REQUEST"
export const ANALYTICS_CHART_SUCCESS = "ANALYTICS_CHART_SUCCESS"
export const ANALYTICS_CHART_FAIL = "ANALYTICS_CHART_FAIL"

