export const ANALYTICS_REQUEST = "ANALYTICS_REQUEST"
export const ANALYTICS_SUCCESS = "ANALYTICS_SUCCESS"
export const ANALYTICS_FAIL = "ANALYTICS_FAIL"

export const ANALYTICS_CHART_REQUEST = "ANALYTICS_CHART_REQUEST"
export const ANALYTICS_CHART_SUCCESS = "ANALYTICS_CHART_SUCCESS"
export const ANALYTICS_CHART_FAIL = "ANALYTICS_CHART_FAIL"

export const NEW_USER_REQUEST = "NEW_USER_REQUEST"
export const NEW_USER_SUCCESS = "NEW_USER_SUCCESS"
export const NEW_USER_FAIL = "NEW_USER_FAIL"

export const TICKET_DONUT_REQUEST = "TICKET_DONUT_REQUEST"
export const TICKET_DONUT_SUCCESS = "TICKET_DONUT_SUCCESS"
export const TICKET_DONUT_FAIL = "TICKET_DONUT_FAIL"

