export const ANALYTICS_REQUEST = "ANALYTICS_REQUEST"
export const ANALYTICS_SUCCESS = "ANALYTICS_SUCCESS"
export const ANALYTICS_FAIL = "ANALYTICS_FAIL"

export const ANALYTICS_CHART_REQUEST = "ANALYTICS_CHART_REQUEST"
export const ANALYTICS_CHART_SUCCESS = "ANALYTICS_CHART_SUCCESS"
export const ANALYTICS_CHART_FAIL = "ANALYTICS_CHART_FAIL"

export const NEW_USER_REQUEST = "NEW_USER_REQUEST"
export const NEW_USER_SUCCESS = "NEW_USER_SUCCESS"
export const NEW_USER_FAIL = "NEW_USER_FAIL"

export const TICKET_DONUT_REQUEST = "TICKET_DONUT_REQUEST"
export const TICKET_DONUT_SUCCESS = "TICKET_DONUT_SUCCESS"
export const TICKET_DONUT_FAIL = "TICKET_DONUT_FAIL"

export const CURRENT_DATE_REQUEST = "CURRENT_DATE_REQUEST"
export const CURRENT_DATE_SUCCESS = "CURRENT_DATE_SUCCESS"
export const CURRENT_DATE_FAIL = "CURRENT_DATE_FAIL"

export const CHART_ENTERPRISE_REQUEST = "CHART_ENTERPRISE_REQUEST"
export const CHART_ENTERPRISE_SUCCESS = "CHART_ENTERPRISE_SUCCESS"
export const CHART_ENTERPRISE_FAIL = "CHART_ENTERPRISE_FAIL"

export const LIST_ENTERPRISE_REQUEST = "LIST_ENTERPRISE_REQUEST"
export const LIST_ENTERPRISE_SUCCESS = "LIST_ENTERPRISE_SUCCESS"
export const LIST_ENTERPRISE_FAIL = "LIST_ENTERPRISE_FAIL"

export const NAME_CHART_ENTERPRISE_REQUEST = "NAME_CHART_ENTERPRISE_REQUEST"
export const NAME_CHART_ENTERPRISE_SUCCESS = "NAME_CHART_ENTERPRISE_SUCCESS"
export const NAME_CHART_ENTERPRISE_FAIL = "NAME_CHART_ENTERPRISE_FAIL"

export const LAST_ORDER_REQUEST = "LAST_ORDER_REQUEST"
export const LAST_ORDER_SUCCESS = "LAST_ORDER_SUCCESS"
export const LAST_ORDER_FAIL = "LAST_ORDER_FAIL"

